#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-airlift
Version  : 0.153
Release  : 1
URL      : https://github.com/airlift/airlift/archive/0.153.tar.gz
Source0  : https://github.com/airlift/airlift/archive/0.153.tar.gz
Source1  : https://repo1.maven.org/maven2/io/airlift/configuration/0.153/configuration-0.153.jar
Source2  : https://repo1.maven.org/maven2/io/airlift/configuration/0.153/configuration-0.153.pom
Source3  : https://repo1.maven.org/maven2/io/airlift/log/0.153/log-0.153.jar
Source4  : https://repo1.maven.org/maven2/io/airlift/log/0.153/log-0.153.pom
Source5  : https://repo1.maven.org/maven2/io/airlift/stats/0.153/stats-0.153.jar
Source6  : https://repo1.maven.org/maven2/io/airlift/stats/0.153/stats-0.153.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-airlift-data = %{version}-%{release}
Requires: mvn-airlift-license = %{version}-%{release}

%description
# Airlift
[![Maven Central](https://img.shields.io/maven-central/v/io.airlift/airlift.svg?label=Maven%20Central)](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22io.airlift%22)
[![Build Status](https://travis-ci.org/airlift/airlift.svg?branch=master)](https://travis-ci.org/airlift/airlift)

%package data
Summary: data components for the mvn-airlift package.
Group: Data

%description data
data components for the mvn-airlift package.


%package license
Summary: license components for the mvn-airlift package.
Group: Default

%description license
license components for the mvn-airlift package.


%prep
%setup -q -n airlift-0.153

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-airlift
cp LICENSE %{buildroot}/usr/share/package-licenses/mvn-airlift/LICENSE
cp src/license/LICENSE-HEADER.txt %{buildroot}/usr/share/package-licenses/mvn-airlift/src_license_LICENSE-HEADER.txt
mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/airlift/configuration/0.153
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/io/airlift/configuration/0.153/configuration-0.153.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/airlift/configuration/0.153
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/io/airlift/configuration/0.153/configuration-0.153.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/airlift/log/0.153
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/io/airlift/log/0.153/log-0.153.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/airlift/log/0.153
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/io/airlift/log/0.153/log-0.153.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/airlift/stats/0.153
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/io/airlift/stats/0.153/stats-0.153.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/airlift/stats/0.153
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/io/airlift/stats/0.153/stats-0.153.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/io/airlift/configuration/0.153/configuration-0.153.jar
/usr/share/java/.m2/repository/io/airlift/configuration/0.153/configuration-0.153.pom
/usr/share/java/.m2/repository/io/airlift/log/0.153/log-0.153.jar
/usr/share/java/.m2/repository/io/airlift/log/0.153/log-0.153.pom
/usr/share/java/.m2/repository/io/airlift/stats/0.153/stats-0.153.jar
/usr/share/java/.m2/repository/io/airlift/stats/0.153/stats-0.153.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-airlift/LICENSE
/usr/share/package-licenses/mvn-airlift/src_license_LICENSE-HEADER.txt
